# Copyright 2021 walt@javins.net
# Use of this code is governed by the GNU GPLv3 found in the LICENSE file.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone-fork-approval-extension.fullname" . }}
  labels:
    {{- include "drone-fork-approval-extension.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drone-fork-approval-extension.selectorLabels" . | nindent 4 }}
